name: ci-python-unittest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Antlr4
        uses: StoneMoe/setup-antlr4@v4.13.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install antlr4-python3-runtime boto3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Antlr4
        run: antlr4 -Dlanguage=Python3 grammar/Onion.g4 -visitor -o generated
          
      - name: Test with unittest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python test.py
