name: ci-python-unittest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      # 1) checkout
      - uses: actions/checkout@v3

      # 2) install Java 11 (required by ANTLR)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3) download ANTLR-4 CLI and expose `antlr4` on the PATH
      - name: Download ANTLR-4.13.2 and expose antlr4
        run: |
          mkdir -p tools
          curl -sSL https://www.antlr.org/download/antlr-4.13.2-complete.jar \
            -o tools/antlr-4.13.2-complete.jar

          # write a tiny wrapper script called "antlr4"
          cat << 'EOF' > tools/antlr4
          #!/usr/bin/env bash
          java -jar "$PWD/tools/antlr-4.13.2-complete.jar" "$@"
          EOF
          chmod +x tools/antlr4

          # add our tools directory to PATH for subsequent steps
          echo "$PWD/tools" >> $GITHUB_PATH

      # 4) generate Python3 parser & lexer
      - name: Generate ANTLR sources
        run: |
          mkdir -p generated
          antlr4 \
            -Dlanguage=Python3 \
            -visitor \
            -o generated \
            grammar/Onion.g4
          touch generated/__init__.py

      # 5) set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 6) install Python deps (including antlr runtime)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install antlr4-python3-runtime boto3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 7) run your tests
      - name: Test with unittest
        run: python test.py
